version: "3.8"

services:
  db:
    image: postgres:17
    container_name: issue_tracker_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: issue_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: issue_tracker_api
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: sh -c "npx prisma migrate dev --name init && node server.js"

volumes:
  postgres_data:
